"""initial database schema (Phase 2)

Revision ID: 28634803e1f1
Revises: 
Create Date: 2025-12-06 15:11:04.062212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28634803e1f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('base_asset', sa.String(), nullable=False),
    sa.Column('quote_asset', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interval')
    )
    op.create_table('exchange_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('canonical_symbol_id', sa.Integer(), nullable=False),
    sa.Column('exchange_symbol', sa.String(), nullable=False),
    sa.Column('market_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_symbol_id'], ['canonical_symbols.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supported_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_market_id', sa.Integer(), nullable=False),
    sa.Column('interval_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_market_id'], ['exchange_markets.id'], ),
    sa.ForeignKeyConstraint(['interval_id'], ['intervals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supported_markets')
    op.drop_table('exchange_markets')
    op.drop_table('intervals')
    op.drop_table('exchanges')
    op.drop_table('canonical_symbols')
    # ### end Alembic commands ###
